# Generated by Django 5.1.1 on 2024-10-03 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicant_id', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(max_length=255)),
                ('id_doc_type', models.CharField(max_length=255)),
                ('image_ids', models.JSONField()),
                ('image_review_results', models.JSONField(blank=True, null=True)),
                ('forbidden', models.BooleanField(default=False)),
                ('partial_completion', models.BooleanField(blank=True, null=True)),
                ('step_statuses', models.JSONField(blank=True, null=True)),
                ('image_statuses', models.JSONField(blank=True, null=True)),
                ('selfie', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
